import { useLocalSearchParams, useRouter } from 'expo-router';
import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useAuth } from '../../src/auth';
import { api, type SubmissionDetail } from '../../src/api';
import { PrimaryButton, Section } from '../../src/components/ui';
import { colors, radius, spacing } from '../../src/theme';

const PRIORITY_COLORS: Record<string, string> = {
  urgent: '#b91c1c',
  high: '#c2410c',
  medium: '#a16207',
  low: '#15803d',
};

export default function SubmissionDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const router = useRouter();
  const { token, loading: authLoading } = useAuth();
  const [submission, setSubmission] = useState<SubmissionDetail | null>(null);
  const [loading, setLoading] = useState(true);
  const [regenerating, setRegenerating] = useState(false);

  const load = useCallback(async () => {
    if (!token || !id) return;
    const detail = await api.getSubmissionDetail(token, id);
    setSubmission(detail);
  }, [token, id]);

  useEffect(() => {
    if (!authLoading && !token) {
      router.replace('/portal/login');
      return;
    }
    if (token) {
      load()
        .catch(() => {})
        .finally(() => setLoading(false));
    }
  }, [authLoading, token, load, router]);

  async function regenerate() {
    if (!token || !id) return;
    setRegenerating(true);
    try {
      const summary = await api.regenerateAiSummary(token, id);
      setSubmission((prev) => (prev ? { ...prev, aiSummary: summary } : prev));
    } finally {
      setRegenerating(false);
    }
  }

  if (loading || !submission) {
    return (
      <View style={styles.center}>
        <ActivityIndicator color={colors.primary} />
      </View>
    );
  }

  const ai = submission.aiSummary;
  const d = submission.data;

  return (
    <ScrollView contentContainerStyle={styles.container}>
      <Text style={styles.name}>{submission.customerName}</Text>
      <Text style={styles.muted}>
        {submission.status} · {submission.vehicleInfo ?? 'No vehicle'}
      </Text>

      <Section title="AI Triage">
        {ai ? (
          <View>
            <View style={[styles.priorityBadge, { backgroundColor: PRIORITY_COLORS[ai.priority] ?? colors.muted }]}>
              <Text style={styles.priorityText}>{ai.priority.toUpperCase()}</Text>
            </View>
            <Text style={styles.label}>Why</Text>
            <Text style={styles.value}>{ai.priorityReason}</Text>
            <Text style={styles.label}>Summary</Text>
            <Text style={styles.value}>{ai.summary}</Text>
            {ai.missingInfo.length > 0 && (
              <>
                <Text style={styles.label}>Missing info</Text>
                {ai.missingInfo.map((m) => (
                  <Text key={m} style={styles.bullet}>
                    • {m}
                  </Text>
                ))}
              </>
            )}
            <Text style={styles.label}>Suggested next action</Text>
            <Text style={styles.value}>{ai.suggestedNextAction}</Text>
            <Text style={styles.tiny}>
              Generated by {ai.generatedBy} at {new Date(ai.generatedAt).toLocaleString()}
            </Text>
          </View>
        ) : (
          <Text style={styles.muted}>No AI summary yet.</Text>
        )}
        <View style={{ marginTop: spacing.md }}>
          <PrimaryButton title="Regenerate AI summary" loading={regenerating} onPress={regenerate} />
        </View>
      </Section>

      <Section title="Contact">
        <Field label="Name" value={d.contact?.fullName} />
        <Field label="Phone" value={d.contact?.phone} />
        <Field label="Email" value={d.contact?.email} />
      </Section>

      <Section title="Insurance">
        <Field label="Company" value={d.insurance?.companyName} />
        <Field label="Policy #" value={d.insurance?.policyNumber} />
        <Field label="Claim #" value={d.insurance?.claimNumber} />
      </Section>

      <Section title="Vehicle">
        <Field label="Vehicle" value={submission.vehicleInfo} />
        <Field label="VIN" value={d.vehicle?.vin} />
        <Field label="Plate" value={d.vehicle?.licensePlate} />
        <Field label="Damage" value={d.vehicle?.damageDescription} />
      </Section>

      <Section title="Claim">
        <Field label="Accident date" value={d.claim?.accidentDate} />
        <Field label="Location" value={d.claim?.accidentLocation} />
        <Field label="At fault" value={d.claim?.atFault} />
      </Section>

      <Section title={`Attachments (${submission.attachments.length})`}>
        {submission.attachments.length === 0 ? (
          <Text style={styles.muted}>None uploaded.</Text>
        ) : (
          submission.attachments.map((a) => (
            <Text key={a.id} style={styles.value}>
              {a.kind} — {a.fileName} ({Math.round(a.sizeBytes / 1024)} KB)
            </Text>
          ))
        )}
      </Section>
    </ScrollView>
  );
}

function Field({ label, value }: { label: string; value?: string | number | null }) {
  if (!value) return null;
  return (
    <View style={{ marginBottom: spacing.sm }}>
      <Text style={styles.label}>{label}</Text>
      <Text style={styles.value}>{value}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  center: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  container: { padding: spacing.lg },
  name: { fontSize: 22, fontWeight: '800', color: colors.text },
  muted: { fontSize: 13, color: colors.muted, marginBottom: spacing.md },
  label: { fontSize: 12, color: colors.muted, fontWeight: '600', marginTop: spacing.xs },
  value: { fontSize: 15, color: colors.text, marginBottom: spacing.xs },
  bullet: { fontSize: 14, color: colors.text, marginLeft: spacing.xs },
  tiny: { fontSize: 11, color: colors.muted, marginTop: spacing.sm },
  priorityBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: radius.sm,
    marginBottom: spacing.sm,
  },
  priorityText: { color: '#fff', fontWeight: '800', fontSize: 12 },
});

