import type { DamageAssessment, DamageSeverity } from '@autobody/shared';
import { config, hasOpenAI } from '../../config/index.js';

/**
 * AI damage assessment — see estimate.contracts.ts for the full rationale.
 * Analyzes up to a handful of damage photos + the customer's written
 * description to give staff an instant severity/scope read before anyone
 * has physically looked at the car.
 */
export interface AssessDamageInput {
  damageDescription?: string;
  vehicleInfo: string | null;
  /** Damage photo bytes (already filtered to image/* content types), capped by the caller. */
  images: Array<{ buffer: Buffer; contentType: string }>;
}

const SEVERE_KEYWORDS = ['totaled', 'total loss', 'frame', 'airbag', 'rollover', 'undrivable', 'engine'];
const MODERATE_KEYWORDS = ['bumper', 'fender', 'door', 'panel', 'headlight', 'taillight', 'quarter panel'];

function assessWithRules(input: AssessDamageInput): DamageAssessment {
  const desc = (input.damageDescription ?? '').toLowerCase();
  const photoCount = input.images.length;

  let severity: DamageSeverity = 'minor';
  if (SEVERE_KEYWORDS.some((k) => desc.includes(k))) {
    severity = 'severe';
  } else if (MODERATE_KEYWORDS.some((k) => desc.includes(k)) || photoCount >= 3) {
    severity = 'moderate';
  }

  const ranges: Record<DamageSeverity, { hours: [number, number]; cost: [number, number] }> = {
    minor: { hours: [2, 8], cost: [300, 1500] },
    moderate: { hours: [8, 24], cost: [1500, 5000] },
    severe: { hours: [24, 60], cost: [5000, 15000] },
    total_loss_likely: { hours: [0, 0], cost: [0, 0] },
  };
  const r = ranges[severity];

  return {
    severity,
    affectedAreas: photoCount > 0 ? [`${photoCount} damage photo(s) provided — review for exact panels`] : [],
    repairComplexity: input.damageDescription
      ? `Based on the customer's description: "${input.damageDescription.slice(0, 200)}"`
      : 'No damage description provided — assessment based on photo count only.',
    estimatedLaborHours: { min: r.hours[0], max: r.hours[1] },
    estimatedCostRange: { min: r.cost[0], max: r.cost[1], currency: 'USD' },
    recommendation:
      photoCount === 0
        ? 'No damage photos uploaded yet — request photos before scheduling an estimate.'
        : 'Have an estimator confirm scope in person; this is a rough triage read only.',
    disclaimer:
      'This is an automated, non-binding triage estimate generated from limited information. It is NOT a certified repair estimate.',
    confidence: 'low',
    generatedBy: 'rules',
    generatedAt: new Date().toISOString(),
  };
}

async function assessWithOpenAI(input: AssessDamageInput): Promise<DamageAssessment> {
  const imageParts = input.images.slice(0, 6).map((img) => ({
    type: 'image_url' as const,
    image_url: { url: `data:${img.contentType};base64,${img.buffer.toString('base64')}` },
  }));

  const textPrompt = `You are a senior collision-repair estimator doing a QUICK triage read (not a formal estimate) on a vehicle's damage photos${
    input.vehicleInfo ? ` (${input.vehicleInfo})` : ''
  }.${input.damageDescription ? ` Customer's description: "${input.damageDescription}"` : ''}

Respond with ONLY a JSON object matching this shape:
{
  "severity": "minor"|"moderate"|"severe"|"total_loss_likely",
  "affectedAreas": string[],
  "repairComplexity": string,
  "estimatedLaborHours": {"min": number, "max": number},
  "estimatedCostRange": {"min": number, "max": number, "currency": "USD"},
  "recommendation": string,
  "confidence": "low"|"medium"|"high"
}
Be conservative and give WIDE ranges — this is a rough triage read, not a quote.`;

  const res = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${config.OPENAI_API_KEY}`,
    },
    body: JSON.stringify({
      model: config.AI_MODEL,
      messages: [
        {
          role: 'user',
          content: [{ type: 'text', text: textPrompt }, ...imageParts],
        },
      ],
      response_format: { type: 'json_object' },
      temperature: 0.2,
    }),
  });

  if (!res.ok) throw new Error(`OpenAI request failed: ${res.status}`);
  const body = (await res.json()) as { choices: Array<{ message: { content: string } }> };
  const content = body.choices[0]?.message.content;
  if (!content) throw new Error('OpenAI response had no content');
  const parsed = JSON.parse(content) as Omit<
    DamageAssessment,
    'disclaimer' | 'generatedBy' | 'generatedAt'
  >;

  return {
    ...parsed,
    disclaimer:
      'This is an automated, non-binding triage estimate generated by AI from photos. It is NOT a certified repair estimate.',
    generatedBy: 'openai',
    generatedAt: new Date().toISOString(),
  };
}

/**
 * Assess damage severity/scope. Tries OpenAI Vision when configured (and at
 * least one image is present); always falls back to the deterministic rule
 * engine on any failure — this is a nice-to-have triage aid, never a
 * blocker for the core intake flow.
 */
export async function assessDamage(input: AssessDamageInput): Promise<DamageAssessment> {
  if (hasOpenAI && input.images.length > 0) {
    try {
      return await assessWithOpenAI(input);
    } catch (err) {
      // eslint-disable-next-line no-console
      console.warn('[estimate] OpenAI damage assessment failed, falling back to rules:', (err as Error).message);
    }
  }
  return assessWithRules(input);
}

