/**
 * Legal document content — served as plain text at GET /legal/terms and
 * GET /legal/privacy (see legal.routes.ts). Kept as TypeScript string
 * constants (not standalone .md files) so they compile into backend/dist
 * automatically with everything else — the Docker image only copies
 * backend/dist, not backend/src, so a loose asset file would silently not
 * ship to production.
 *
 * ⚠️ IMPORTANT: this is a solid starting template covering the specific
 * things this product actually does (PII collection, SMS/TCPA, AI
 * processing, third-party subprocessors), but it is NOT a substitute for
 * review by a licensed attorney in your jurisdiction before public launch.
 * Update COMPANY_NAME/CONTACT_EMAIL/GOVERNING_LAW below and get it reviewed.
 */

export const COMPANY_NAME = 'AutoBody Intake';
export const CONTACT_EMAIL = 'legal@example.com'; // TODO: replace before launch
export const GOVERNING_LAW = 'the State of Delaware, USA'; // TODO: confirm with counsel
export const LAST_UPDATED = 'September 23, 2026';

export const TERMS_OF_SERVICE = `${COMPANY_NAME} — Terms of Service
Last updated: ${LAST_UPDATED}

⚠️ TEMPLATE NOTICE: This document is a starting point covering the core
functionality of this product. It has not been reviewed by an attorney and
should be before relying on it for a public launch.

1. ACCEPTANCE OF TERMS
By creating a shop account ("Account") or otherwise using ${COMPANY_NAME}
(the "Service"), you agree to be bound by these Terms of Service ("Terms").
If you do not agree, do not use the Service.

2. DESCRIPTION OF SERVICE
${COMPANY_NAME} provides collision repair shops with a customer-intake
platform: a shareable link/QR code that collects a customer's contact,
insurance, vehicle, and accident information; packages it for the shop;
and provides AI-assisted triage, damage assessment, status-update drafting,
and insurance-adjuster follow-up drafting. The Service is a workflow tool
and does not replace professional judgment — every AI-generated output
(triage priority, damage assessment, drafted message) is a suggestion for a
human to review, edit, and approve before acting on it.

3. ACCOUNTS
You must provide accurate information when creating an Account and are
responsible for maintaining the confidentiality of your login credentials
and for all activity under your Account, including actions taken by staff
members you invite. Notify us immediately of any unauthorized use.

4. CUSTOMER DATA — YOUR RESPONSIBILITIES
Your customers submit personal information (name, contact info, driver's
license, insurance details, vehicle photos) directly to your shop through
the Service. You are the data controller for that information under
applicable law; ${COMPANY_NAME} processes it on your behalf as a data
processor/service provider. You are responsible for:
  (a) ensuring you have a lawful basis and appropriate customer notice/
      consent for collecting and using this data (see our Privacy Policy
      for the notice language built into the intake form);
  (b) obtaining explicit SMS consent from customers before requesting the
      Service send them automated text messages (the intake form includes
      a TCPA-compliant opt-in checkbox for this — do not attempt to work
      around it);
  (c) complying with insurance, consumer-protection, and data-protection
      laws applicable to your business and jurisdiction.

5. AI-GENERATED CONTENT
Triage priorities, damage/cost estimates, and drafted customer/adjuster
messages are generated by automated systems (rule-based logic and/or a
third-party large language model) and are provided "as-is" for your
review. They are not certified repair estimates, legal advice, or a
guarantee of insurance coverage or claim outcomes. You are solely
responsible for reviewing and approving any AI-drafted communication
before it is sent, and for any repair estimate before it is presented to
a customer or insurer.

6. AUTOMATED FEATURES
Some features (e.g. scheduled adjuster follow-up emails) can be configured
to send communications automatically without a per-message human review
step. Enabling these features is an explicit opt-in action, and you are
responsible for the content and timing of anything sent this way.

7. THIRD-PARTY SUBPROCESSORS
The Service uses third-party providers to function, which may include:
cloud hosting, object storage, transactional email delivery, SMS delivery
(Twilio), and AI/LLM providers (OpenAI). These providers process data only
as necessary to provide the Service and are bound by their own terms and
(where applicable) data processing agreements.

8. FEES
Fees, if any, are as agreed separately (e.g. an order form or invoice) and
are not set by these Terms.

9. TERMINATION
Either party may terminate an Account at any time. We may suspend or
terminate access for violation of these Terms, non-payment, or conduct
that risks harm to the Service, other users, or their customers.

10. DISCLAIMER OF WARRANTIES
THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
NON-INFRINGEMENT. WE DO NOT WARRANT THAT AI-GENERATED OUTPUTS ARE ACCURATE,
COMPLETE, OR SUITABLE FOR ANY PARTICULAR PURPOSE.

11. LIMITATION OF LIABILITY
TO THE MAXIMUM EXTENT PERMITTED BY LAW, ${COMPANY_NAME} SHALL NOT BE LIABLE
FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES,
OR ANY LOSS OF PROFITS OR REVENUE, ARISING FROM YOUR USE OF THE SERVICE.

12. GOVERNING LAW
These Terms are governed by the laws of ${GOVERNING_LAW}, without regard to
conflict-of-law principles.

13. CHANGES
We may update these Terms from time to time. Continued use of the Service
after a change constitutes acceptance of the updated Terms.

14. CONTACT
Questions about these Terms: ${CONTACT_EMAIL}
`;

export const PRIVACY_POLICY = `${COMPANY_NAME} — Privacy Policy
Last updated: ${LAST_UPDATED}

⚠️ TEMPLATE NOTICE: This document is a starting point covering the core
functionality of this product. It has not been reviewed by an attorney and
should be before relying on it for a public launch (consider CCPA, GDPR,
and state-level privacy laws applicable to where your shops and their
customers are located).

1. WHO THIS APPLIES TO
This Privacy Policy covers two groups:
  • Shop accounts — the repair shop staff who sign up for and use the
    Service directly.
  • Customers — people who submit information through a shop's intake
    link after an accident. Customers do not create an account; their
    submission is associated with the shop they submitted it to.

2. INFORMATION WE COLLECT
  Shop accounts: shop name, address, phone, staff/owner email addresses,
  a hashed password, and usage data.

  Customers (submitted via the intake form): full name, phone, email,
  insurance company/policy/claim number and adjuster contact, driver's
  license photo and extracted fields, vehicle info (year/make/model/VIN/
  plate/mileage), damage photos, accident details (date/location/police
  report/other-party info), rental-coverage preferences, and — only with
  explicit opt-in at the time of submission — consent to receive automated
  SMS status updates about their repair.

3. HOW WE USE INFORMATION
  • To deliver the submitted information to the shop the customer chose.
  • To generate AI-assisted triage summaries, damage assessments, and
    drafted status-update/adjuster-follow-up messages for shop staff to
    review before sending.
  • To send status updates via SMS (only to customers who opted in) or
    email, at the direction of shop staff, or automatically for adjuster
    follow-ups if a shop has enabled that feature.
  • To operate, secure, and improve the Service.
We do not sell personal information.

4. AI PROCESSING
Photos and text submitted may be sent to a third-party AI provider
(OpenAI) to generate document data extraction (OCR), damage assessments,
and drafted messages. This processing is transient (used to generate a
response) and governed by that provider's own data-use terms for API
customers, which — as of this writing — do not use API-submitted content
to train their models.

5. SMS / TEXT MESSAGES
If a customer explicitly opts in at intake, the shop may send automated
status-update texts via Twilio. Message and data rates may apply. Message
frequency varies by repair status. Customers may reply STOP at any time to
opt out of future messages; replies are logged and visible to shop staff
so they can follow up by another channel if needed.

6. DATA RETENTION
Submission records (including photos and documents) are retained for as
long as the shop's account is active, to support the repair workflow and
the shop's own record-keeping needs. Shops may request deletion of a
specific customer's data (see Section 8) or of their entire account's data
upon account closure.

7. THIRD-PARTY SERVICE PROVIDERS
We use the following categories of subprocessors to operate the Service:
cloud hosting/compute, managed database hosting, object storage (photos/
documents), transactional email delivery, SMS delivery (Twilio), and AI/
LLM processing (OpenAI). Each only receives the data necessary to perform
its function.

8. YOUR RIGHTS
Depending on your location, you may have rights to access, correct, or
request deletion of your personal information. Shop staff can reach us at
${CONTACT_EMAIL} to request deletion of a specific customer's submission
data; customers should contact the shop they submitted information to
directly, since the shop — not ${COMPANY_NAME} — is the primary point of
contact for their repair.

9. SECURITY
Data is encrypted in transit (HTTPS/TLS) and access to shop data is
strictly isolated per shop account. No system is 100% secure; we can't
guarantee absolute security but take reasonable measures appropriate to
the sensitivity of the data involved.

10. CHILDREN
The Service is not directed at children and is not intended to collect
information from anyone under 18.

11. CHANGES
We may update this Privacy Policy from time to time; the "Last updated"
date above will reflect the most recent revision.

12. CONTACT
Questions about this Privacy Policy: ${CONTACT_EMAIL}
`;

